--
-- JBoss, Home of Professional Open Source
-- Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
-- contributors by the @authors tag. See the copyright.txt in the
-- distribution for a full listing of individual contributors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- http://www.apache.org/licenses/LICENSE-2.0
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- You can use this file to load seed data into the database using SQL statements


create table question(
 id bigint PRIMARY KEY NOT NULL Generated By Default As Identity,
 text varchar(512)
);
create table answer(
 id bigint PRIMARY KEY NOT NULL Generated By Default As Identity,
 text varchar(512),
 question_id bigint
);
create table survey(
 id bigint PRIMARY KEY NOT NULL Generated By Default As Identity,
 question_id bigint,
 answer_id bigint
);

insert into question(id, text) values (1, 'Question1');
insert into answer(id, question_Id, text) values (1, 1, 'Answer1');
insert into answer(id, question_Id, text) values (2, 1, 'Answer2');
